# App Engine app's settings
# https://cloud.google.com/appengine/docs/standard/python3/config/appref
runtime: python38
service: default
instance_class: F2
entrypoint: cd meridiem && python manage.py runserver 0.0.0.0:$PORT
handlers:
- url: /.*
  script: auto
# env_variables:
    #  DJANGO_SETTINGS_MODULE: 'config.settings.production'
    #  DEBUG: 'False'

